// <auto-generated />
namespace MW.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MemorizeWords : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MemorizeWords));
        
        string IMigrationMetadata.Id
        {
            get { return "201907241659254_MemorizeWords"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
